// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TracklyApi.Data;

#nullable disable

namespace TracklyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231215114316_ClassesUpdateMigration")]
    partial class ClassesUpdateMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TracklyApi.Models.Asset", b =>
                {
                    b.Property<Guid>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssetID");

                    b.HasIndex("BarcodeNumber")
                        .IsUnique();

                    b.HasIndex("DepartmentID");

                    b.HasIndex("LocationID");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetID = new Guid("51b6fd0f-aabe-43a3-ade5-33c3c254c8e9"),
                            AssetName = "Asset 1",
                            BarcodeNumber = "100000000000",
                            Category = 0,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("d7ada6a1-084e-412c-8037-ea84bad83ef3"),
                            AssetName = "Asset 2",
                            BarcodeNumber = "100000000001",
                            Category = 1,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("2f59c1b4-aa71-451a-be9c-1cfd23673305"),
                            AssetName = "Asset 3",
                            BarcodeNumber = "100000000002",
                            Category = 2,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("cb7993e1-355c-4af1-9acc-bd7d49b96177"),
                            AssetName = "Asset 4",
                            BarcodeNumber = "100000000003",
                            Category = 3,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("e755ae09-7715-4a9c-b311-9cab13534e59"),
                            AssetName = "Asset 5",
                            BarcodeNumber = "100000000004",
                            Category = 4,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("e30b1963-42cf-47d3-9926-f8e4ffbe1021"),
                            AssetName = "Asset 6",
                            BarcodeNumber = "100000000005",
                            Category = 5,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("2068321b-f4c2-47ee-853d-298dba676ab8"),
                            AssetName = "Asset 7",
                            BarcodeNumber = "100000000006",
                            Category = 6,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("810a0307-e4b4-4628-a81c-eec6c5f1d66d"),
                            AssetName = "Asset 8",
                            BarcodeNumber = "100000000007",
                            Category = 0,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("5613d2de-c16d-4cdc-830e-2e4773614f48"),
                            AssetName = "Asset 9",
                            BarcodeNumber = "100000000008",
                            Category = 1,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("e6b0147b-083c-426b-af19-ef8ab0afda67"),
                            AssetName = "Asset 10",
                            BarcodeNumber = "100000000009",
                            Category = 2,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("8753f5c5-2f3e-4f38-97f4-2864a1735c85"),
                            AssetName = "Asset 11",
                            BarcodeNumber = "100000000010",
                            Category = 3,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("f5129329-1cc5-4df9-b145-ae555e95e8f6"),
                            AssetName = "Asset 12",
                            BarcodeNumber = "100000000011",
                            Category = 4,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("0dd2ea81-25aa-4309-863a-b525e10d7160"),
                            AssetName = "Asset 13",
                            BarcodeNumber = "100000000012",
                            Category = 5,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("5cc0e93e-fbc8-4068-9d92-2b33cd72b30f"),
                            AssetName = "Asset 14",
                            BarcodeNumber = "100000000013",
                            Category = 6,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("627b0b34-7836-4a70-be6f-af0d79c89723"),
                            AssetName = "Asset 15",
                            BarcodeNumber = "100000000014",
                            Category = 0,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("1acaab62-c14e-4e99-b662-e4810572dcf3"),
                            AssetName = "Asset 16",
                            BarcodeNumber = "100000000015",
                            Category = 1,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("c3093c85-90fc-4943-9a5f-514ec11e005b"),
                            AssetName = "Asset 17",
                            BarcodeNumber = "100000000016",
                            Category = 2,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("45f9036e-e4bb-45a3-a68e-7577f2c94dd9"),
                            AssetName = "Asset 18",
                            BarcodeNumber = "100000000017",
                            Category = 3,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("9ba06a74-bacc-493e-beac-e8bb4a26c4b2"),
                            AssetName = "Asset 19",
                            BarcodeNumber = "100000000018",
                            Category = 4,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("74200675-537f-401a-bd14-9ea38d0ff550"),
                            AssetName = "Asset 20",
                            BarcodeNumber = "100000000019",
                            Category = 5,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("e2b099a8-b23f-4607-87fa-61852fe7e1a0"),
                            AssetName = "Asset 21",
                            BarcodeNumber = "100000000020",
                            Category = 6,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("21f12b7c-b699-48d7-88af-a79e48eea75d"),
                            AssetName = "Asset 22",
                            BarcodeNumber = "100000000021",
                            Category = 0,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("2b6e0017-67dc-478e-af07-be3d4257e24d"),
                            AssetName = "Asset 23",
                            BarcodeNumber = "100000000022",
                            Category = 1,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("8400ca54-619f-4339-9f5a-07a2268f3541"),
                            AssetName = "Asset 24",
                            BarcodeNumber = "100000000023",
                            Category = 2,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("c0cf60f6-3100-4d07-ae50-c93d13d657b8"),
                            AssetName = "Asset 25",
                            BarcodeNumber = "100000000024",
                            Category = 3,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("a015f1b9-9f51-4fcf-9d24-ffc40efbd469"),
                            AssetName = "Asset 26",
                            BarcodeNumber = "100000000025",
                            Category = 4,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("114e42ae-b774-4e25-a99a-1f18dfdef8ff"),
                            AssetName = "Asset 27",
                            BarcodeNumber = "100000000026",
                            Category = 5,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("53a75513-1196-409c-8f32-9dae9efd1c24"),
                            AssetName = "Asset 28",
                            BarcodeNumber = "100000000027",
                            Category = 6,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("81504d3d-ca25-402b-b635-16c80801d0f5"),
                            AssetName = "Asset 29",
                            BarcodeNumber = "100000000028",
                            Category = 0,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("17ffde7e-6ae5-45ee-8bc0-f59ebb1fb5b9"),
                            AssetName = "Asset 30",
                            BarcodeNumber = "100000000029",
                            Category = 1,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("76bb6409-8a56-44be-b7bf-57941b0a643f"),
                            AssetName = "Asset 31",
                            BarcodeNumber = "100000000030",
                            Category = 2,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("1860eecd-d80c-46a1-814c-e08a32f4405d"),
                            AssetName = "Asset 32",
                            BarcodeNumber = "100000000031",
                            Category = 3,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("544cb425-ff69-41fd-8682-e3fbadd8983d"),
                            AssetName = "Asset 33",
                            BarcodeNumber = "100000000032",
                            Category = 4,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("4c8de5a4-ae88-479a-b2ec-7d251382f6c8"),
                            AssetName = "Asset 34",
                            BarcodeNumber = "100000000033",
                            Category = 5,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("690df44e-f789-43b7-8903-65cc75d91a7b"),
                            AssetName = "Asset 35",
                            BarcodeNumber = "100000000034",
                            Category = 6,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("2826706c-9e41-4b31-97d8-642d1f55f519"),
                            AssetName = "Asset 36",
                            BarcodeNumber = "100000000035",
                            Category = 0,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("60503af3-7b14-4d38-81ba-7a0998563ef7"),
                            AssetName = "Asset 37",
                            BarcodeNumber = "100000000036",
                            Category = 1,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("30d23da0-3af0-480f-b55b-73fb05a33134"),
                            AssetName = "Asset 38",
                            BarcodeNumber = "100000000037",
                            Category = 2,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("140658dd-ec46-4063-86be-f030a3ff5444"),
                            AssetName = "Asset 39",
                            BarcodeNumber = "100000000038",
                            Category = 3,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("35487d71-7908-447d-a94f-2f8345b9e3a0"),
                            AssetName = "Asset 40",
                            BarcodeNumber = "100000000039",
                            Category = 4,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("b03606a9-d74e-48ad-9d50-310f182ceb35"),
                            AssetName = "Asset 41",
                            BarcodeNumber = "100000000040",
                            Category = 5,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("896b7942-9e6e-4897-8ed6-dfcf8656263c"),
                            AssetName = "Asset 42",
                            BarcodeNumber = "100000000041",
                            Category = 6,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("ea076f57-798a-4b54-bae9-d4571d1f8b2d"),
                            AssetName = "Asset 43",
                            BarcodeNumber = "100000000042",
                            Category = 0,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("fee00f91-b440-4ec0-83f6-e45d864444d5"),
                            AssetName = "Asset 44",
                            BarcodeNumber = "100000000043",
                            Category = 1,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("e76f38c0-a41d-4ae2-ae16-fef88a01939e"),
                            AssetName = "Asset 45",
                            BarcodeNumber = "100000000044",
                            Category = 2,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("f219cd48-ed87-4198-a54c-58aa1ca36c41"),
                            AssetName = "Asset 46",
                            BarcodeNumber = "100000000045",
                            Category = 3,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("027fc934-87bf-455f-a888-b1eee80db06c"),
                            AssetName = "Asset 47",
                            BarcodeNumber = "100000000046",
                            Category = 4,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("c9fb754e-37b6-433f-90c2-14d3596f7daa"),
                            AssetName = "Asset 48",
                            BarcodeNumber = "100000000047",
                            Category = 5,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("0f2e0084-19a9-46a6-bf4c-c353e51bf150"),
                            AssetName = "Asset 49",
                            BarcodeNumber = "100000000048",
                            Category = 6,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("3a709247-02c1-4c9e-ac17-251fdff5e14a"),
                            AssetName = "Asset 50",
                            BarcodeNumber = "100000000049",
                            Category = 0,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("8d1abc59-c589-461f-9b97-37c2f934a5db"),
                            AssetName = "Asset 51",
                            BarcodeNumber = "100000000050",
                            Category = 1,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("7928b3da-ab4e-483b-9a2a-dbbb42bc074e"),
                            AssetName = "Asset 52",
                            BarcodeNumber = "100000000051",
                            Category = 2,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("69dbd27c-4a8c-4a7f-8434-d8d0497b16d7"),
                            AssetName = "Asset 53",
                            BarcodeNumber = "100000000052",
                            Category = 3,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("a14cd5f7-3a9f-46e4-bc5b-da9e53e8d4cc"),
                            AssetName = "Asset 54",
                            BarcodeNumber = "100000000053",
                            Category = 4,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("d397155b-40b1-40e1-9ec4-422b9c6178f6"),
                            AssetName = "Asset 55",
                            BarcodeNumber = "100000000054",
                            Category = 5,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("d3b9948b-c027-4e96-bf0f-6e0cf8609313"),
                            AssetName = "Asset 56",
                            BarcodeNumber = "100000000055",
                            Category = 6,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("5555f45f-fb76-4b95-a3ed-35618522abd8"),
                            AssetName = "Asset 57",
                            BarcodeNumber = "100000000056",
                            Category = 0,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("7fdf665d-cb16-438f-a6b9-0821dacaa467"),
                            AssetName = "Asset 58",
                            BarcodeNumber = "100000000057",
                            Category = 1,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("7caecff8-071f-42ab-a774-3008779c4faa"),
                            AssetName = "Asset 59",
                            BarcodeNumber = "100000000058",
                            Category = 2,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("3ec157a3-930b-47e3-b80e-0e81decb0caa"),
                            AssetName = "Asset 60",
                            BarcodeNumber = "100000000059",
                            Category = 3,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("1cd4cb1a-0c02-44b1-9922-e6719a44c2f6"),
                            AssetName = "Asset 61",
                            BarcodeNumber = "100000000060",
                            Category = 4,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("9d7e87f1-bede-4f1b-80c6-dd2e9a825c26"),
                            AssetName = "Asset 62",
                            BarcodeNumber = "100000000061",
                            Category = 5,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("6f57fee9-f4b0-483c-8ee6-5f427787e997"),
                            AssetName = "Asset 63",
                            BarcodeNumber = "100000000062",
                            Category = 6,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("989c5ee8-b4c6-4051-ba87-97848184a088"),
                            AssetName = "Asset 64",
                            BarcodeNumber = "100000000063",
                            Category = 0,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("5a16f00f-1174-4b81-90e7-ed55ea586764"),
                            AssetName = "Asset 65",
                            BarcodeNumber = "100000000064",
                            Category = 1,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("80f5219a-867d-487b-a386-86c0b227d645"),
                            AssetName = "Asset 66",
                            BarcodeNumber = "100000000065",
                            Category = 2,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("550e5af8-81a3-4dff-8299-afe5bd2fa9c0"),
                            AssetName = "Asset 67",
                            BarcodeNumber = "100000000066",
                            Category = 3,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        },
                        new
                        {
                            AssetID = new Guid("18d66df6-fe6f-4fbf-9929-7c4bdcf30974"),
                            AssetName = "Asset 68",
                            BarcodeNumber = "100000000067",
                            Category = 4,
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38")
                        },
                        new
                        {
                            AssetID = new Guid("f8879e79-f94f-4d08-8a2d-6c8d33e849eb"),
                            AssetName = "Asset 69",
                            BarcodeNumber = "100000000068",
                            Category = 5,
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d")
                        },
                        new
                        {
                            AssetID = new Guid("ed8af95e-97d0-4f28-84aa-bf2389426964"),
                            AssetName = "Asset 70",
                            BarcodeNumber = "100000000069",
                            Category = 6,
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115")
                        });
                });

            modelBuilder.Entity("TracklyApi.Models.Department", b =>
                {
                    b.Property<Guid>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepartmentName")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = new Guid("e1e781d1-d8d5-4ccb-8a52-119a3e9f0005"),
                            DepartmentName = 0
                        },
                        new
                        {
                            DepartmentID = new Guid("ac0dbc58-5e9b-43b8-b85d-65eaf44af85e"),
                            DepartmentName = 1
                        },
                        new
                        {
                            DepartmentID = new Guid("5e6b841c-f835-450a-b7b8-e5bd15d16baa"),
                            DepartmentName = 2
                        });
                });

            modelBuilder.Entity("TracklyApi.Models.Location", b =>
                {
                    b.Property<Guid>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LocationName")
                        .HasColumnType("int");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = new Guid("e03c4e15-77b7-4926-ba33-b167d90f3115"),
                            LocationName = 0
                        },
                        new
                        {
                            LocationID = new Guid("76e3c408-dd32-4567-a8e9-1abfbbeaff38"),
                            LocationName = 1
                        },
                        new
                        {
                            LocationID = new Guid("b75ee5b7-fe82-4fdf-8579-a98d5751520d"),
                            LocationName = 2
                        });
                });

            modelBuilder.Entity("TracklyApi.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketId");

                    b.HasIndex("AssetId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = new Guid("1a48c1cc-f065-4127-8d3e-75cef6d15d49"),
                            AssetId = new Guid("51b6fd0f-aabe-43a3-ade5-33c3c254c8e9"),
                            Category = 0,
                            Description = "Description for Ticket 1",
                            Priority = 0,
                            Status = 0,
                            Title = "Ticket 1"
                        },
                        new
                        {
                            TicketId = new Guid("57946686-25df-4191-8470-1b47a43a7014"),
                            AssetId = new Guid("d7ada6a1-084e-412c-8037-ea84bad83ef3"),
                            Category = 1,
                            Description = "Description for Ticket 2",
                            Priority = 1,
                            Status = 1,
                            Title = "Ticket 2"
                        },
                        new
                        {
                            TicketId = new Guid("2ca7cfa0-7a51-4288-86c1-6a3992358d06"),
                            AssetId = new Guid("2f59c1b4-aa71-451a-be9c-1cfd23673305"),
                            Category = 2,
                            Description = "Description for Ticket 3",
                            Priority = 2,
                            Status = 2,
                            Title = "Ticket 3"
                        },
                        new
                        {
                            TicketId = new Guid("6980f2d5-698c-489b-a973-36b8309ce54a"),
                            AssetId = new Guid("cb7993e1-355c-4af1-9acc-bd7d49b96177"),
                            Category = 3,
                            Description = "Description for Ticket 4",
                            Priority = 0,
                            Status = 3,
                            Title = "Ticket 4"
                        },
                        new
                        {
                            TicketId = new Guid("22d33b6c-172a-4db2-bd0e-4f26d4e8d934"),
                            AssetId = new Guid("e755ae09-7715-4a9c-b311-9cab13534e59"),
                            Category = 0,
                            Description = "Description for Ticket 5",
                            Priority = 1,
                            Status = 0,
                            Title = "Ticket 5"
                        },
                        new
                        {
                            TicketId = new Guid("fff07359-b12b-4d89-8f8b-950c972e6dd0"),
                            AssetId = new Guid("e30b1963-42cf-47d3-9926-f8e4ffbe1021"),
                            Category = 1,
                            Description = "Description for Ticket 6",
                            Priority = 2,
                            Status = 1,
                            Title = "Ticket 6"
                        },
                        new
                        {
                            TicketId = new Guid("6248667a-0b07-4bf1-a489-03e7f15595ac"),
                            AssetId = new Guid("2068321b-f4c2-47ee-853d-298dba676ab8"),
                            Category = 2,
                            Description = "Description for Ticket 7",
                            Priority = 0,
                            Status = 2,
                            Title = "Ticket 7"
                        },
                        new
                        {
                            TicketId = new Guid("990d7c9c-9a59-4e87-935a-896bd2cc723f"),
                            AssetId = new Guid("810a0307-e4b4-4628-a81c-eec6c5f1d66d"),
                            Category = 3,
                            Description = "Description for Ticket 8",
                            Priority = 1,
                            Status = 3,
                            Title = "Ticket 8"
                        },
                        new
                        {
                            TicketId = new Guid("3f413184-be9d-48cc-95b2-a20af93017d7"),
                            AssetId = new Guid("5613d2de-c16d-4cdc-830e-2e4773614f48"),
                            Category = 0,
                            Description = "Description for Ticket 9",
                            Priority = 2,
                            Status = 0,
                            Title = "Ticket 9"
                        },
                        new
                        {
                            TicketId = new Guid("0c3237e3-fcd1-4f10-8f20-c7e6d53c2330"),
                            AssetId = new Guid("e6b0147b-083c-426b-af19-ef8ab0afda67"),
                            Category = 1,
                            Description = "Description for Ticket 10",
                            Priority = 0,
                            Status = 1,
                            Title = "Ticket 10"
                        },
                        new
                        {
                            TicketId = new Guid("0d9debc4-699e-438f-a58d-58a67a571ebf"),
                            AssetId = new Guid("8753f5c5-2f3e-4f38-97f4-2864a1735c85"),
                            Category = 2,
                            Description = "Description for Ticket 11",
                            Priority = 1,
                            Status = 2,
                            Title = "Ticket 11"
                        },
                        new
                        {
                            TicketId = new Guid("a3896533-1e15-4c5c-846f-dbd66317b70c"),
                            AssetId = new Guid("f5129329-1cc5-4df9-b145-ae555e95e8f6"),
                            Category = 3,
                            Description = "Description for Ticket 12",
                            Priority = 2,
                            Status = 3,
                            Title = "Ticket 12"
                        },
                        new
                        {
                            TicketId = new Guid("3e5fa133-5f32-4b25-b261-4272a29a19a4"),
                            AssetId = new Guid("0dd2ea81-25aa-4309-863a-b525e10d7160"),
                            Category = 0,
                            Description = "Description for Ticket 13",
                            Priority = 0,
                            Status = 0,
                            Title = "Ticket 13"
                        },
                        new
                        {
                            TicketId = new Guid("23f6a18c-3dbf-4bd8-a417-ef71ffbf5712"),
                            AssetId = new Guid("5cc0e93e-fbc8-4068-9d92-2b33cd72b30f"),
                            Category = 1,
                            Description = "Description for Ticket 14",
                            Priority = 1,
                            Status = 1,
                            Title = "Ticket 14"
                        },
                        new
                        {
                            TicketId = new Guid("ae07ed93-153e-4431-89f6-8140b4630cb8"),
                            AssetId = new Guid("627b0b34-7836-4a70-be6f-af0d79c89723"),
                            Category = 2,
                            Description = "Description for Ticket 15",
                            Priority = 2,
                            Status = 2,
                            Title = "Ticket 15"
                        },
                        new
                        {
                            TicketId = new Guid("cdabb399-a717-496a-a08c-cefc926c03b9"),
                            AssetId = new Guid("1acaab62-c14e-4e99-b662-e4810572dcf3"),
                            Category = 3,
                            Description = "Description for Ticket 16",
                            Priority = 0,
                            Status = 3,
                            Title = "Ticket 16"
                        },
                        new
                        {
                            TicketId = new Guid("9ebd1b50-5db9-4a86-b4f0-57391f1e70e6"),
                            AssetId = new Guid("c3093c85-90fc-4943-9a5f-514ec11e005b"),
                            Category = 0,
                            Description = "Description for Ticket 17",
                            Priority = 1,
                            Status = 0,
                            Title = "Ticket 17"
                        },
                        new
                        {
                            TicketId = new Guid("482acade-9072-4ed3-8386-96de1b6ac4e8"),
                            AssetId = new Guid("45f9036e-e4bb-45a3-a68e-7577f2c94dd9"),
                            Category = 1,
                            Description = "Description for Ticket 18",
                            Priority = 2,
                            Status = 1,
                            Title = "Ticket 18"
                        },
                        new
                        {
                            TicketId = new Guid("4af5199f-25b2-472a-828c-a0197a1b741d"),
                            AssetId = new Guid("9ba06a74-bacc-493e-beac-e8bb4a26c4b2"),
                            Category = 2,
                            Description = "Description for Ticket 19",
                            Priority = 0,
                            Status = 2,
                            Title = "Ticket 19"
                        },
                        new
                        {
                            TicketId = new Guid("24890e19-24a8-466d-99b4-6c0e9fb50181"),
                            AssetId = new Guid("74200675-537f-401a-bd14-9ea38d0ff550"),
                            Category = 3,
                            Description = "Description for Ticket 20",
                            Priority = 1,
                            Status = 3,
                            Title = "Ticket 20"
                        },
                        new
                        {
                            TicketId = new Guid("3471833d-bc8a-4597-82aa-c4dc700f8cd5"),
                            AssetId = new Guid("e2b099a8-b23f-4607-87fa-61852fe7e1a0"),
                            Category = 0,
                            Description = "Description for Ticket 21",
                            Priority = 2,
                            Status = 0,
                            Title = "Ticket 21"
                        },
                        new
                        {
                            TicketId = new Guid("776bb8ac-2a28-40c3-bd2e-3a9a7a44d1c8"),
                            AssetId = new Guid("21f12b7c-b699-48d7-88af-a79e48eea75d"),
                            Category = 1,
                            Description = "Description for Ticket 22",
                            Priority = 0,
                            Status = 1,
                            Title = "Ticket 22"
                        },
                        new
                        {
                            TicketId = new Guid("8821222c-4396-4fd2-b279-202ef19dab35"),
                            AssetId = new Guid("2b6e0017-67dc-478e-af07-be3d4257e24d"),
                            Category = 2,
                            Description = "Description for Ticket 23",
                            Priority = 1,
                            Status = 2,
                            Title = "Ticket 23"
                        },
                        new
                        {
                            TicketId = new Guid("3ecf50f0-e345-402a-8a22-aaaca7d626dc"),
                            AssetId = new Guid("8400ca54-619f-4339-9f5a-07a2268f3541"),
                            Category = 3,
                            Description = "Description for Ticket 24",
                            Priority = 2,
                            Status = 3,
                            Title = "Ticket 24"
                        },
                        new
                        {
                            TicketId = new Guid("90cacad0-8a1b-44b1-b66e-7b8e9be0645b"),
                            AssetId = new Guid("c0cf60f6-3100-4d07-ae50-c93d13d657b8"),
                            Category = 0,
                            Description = "Description for Ticket 25",
                            Priority = 0,
                            Status = 0,
                            Title = "Ticket 25"
                        },
                        new
                        {
                            TicketId = new Guid("830eb981-dc4b-48c7-9520-45ca261bda75"),
                            AssetId = new Guid("a015f1b9-9f51-4fcf-9d24-ffc40efbd469"),
                            Category = 1,
                            Description = "Description for Ticket 26",
                            Priority = 1,
                            Status = 1,
                            Title = "Ticket 26"
                        },
                        new
                        {
                            TicketId = new Guid("5819c316-5131-4966-ab20-14305690148a"),
                            AssetId = new Guid("114e42ae-b774-4e25-a99a-1f18dfdef8ff"),
                            Category = 2,
                            Description = "Description for Ticket 27",
                            Priority = 2,
                            Status = 2,
                            Title = "Ticket 27"
                        },
                        new
                        {
                            TicketId = new Guid("465a7b14-36ae-4d04-9860-27e03d4ba1b8"),
                            AssetId = new Guid("53a75513-1196-409c-8f32-9dae9efd1c24"),
                            Category = 3,
                            Description = "Description for Ticket 28",
                            Priority = 0,
                            Status = 3,
                            Title = "Ticket 28"
                        },
                        new
                        {
                            TicketId = new Guid("8e920974-3f62-41b6-8423-178e7b23646f"),
                            AssetId = new Guid("81504d3d-ca25-402b-b635-16c80801d0f5"),
                            Category = 0,
                            Description = "Description for Ticket 29",
                            Priority = 1,
                            Status = 0,
                            Title = "Ticket 29"
                        },
                        new
                        {
                            TicketId = new Guid("f0d4ee4d-4926-40be-a5e8-ac3917260ada"),
                            AssetId = new Guid("17ffde7e-6ae5-45ee-8bc0-f59ebb1fb5b9"),
                            Category = 1,
                            Description = "Description for Ticket 30",
                            Priority = 2,
                            Status = 1,
                            Title = "Ticket 30"
                        },
                        new
                        {
                            TicketId = new Guid("c8428bd9-c0e9-4a2a-91cf-47aa8e3ead6b"),
                            AssetId = new Guid("51b6fd0f-aabe-43a3-ade5-33c3c254c8e9"),
                            Category = 2,
                            Description = "Description for Ticket 31",
                            Priority = 0,
                            Status = 2,
                            Title = "Ticket 31"
                        },
                        new
                        {
                            TicketId = new Guid("81590bc9-a311-4c5c-9aff-fad2f6bb8b7a"),
                            AssetId = new Guid("d7ada6a1-084e-412c-8037-ea84bad83ef3"),
                            Category = 3,
                            Description = "Description for Ticket 32",
                            Priority = 1,
                            Status = 3,
                            Title = "Ticket 32"
                        },
                        new
                        {
                            TicketId = new Guid("10ec5dcf-f67f-4985-94b1-eebda8912478"),
                            AssetId = new Guid("2f59c1b4-aa71-451a-be9c-1cfd23673305"),
                            Category = 0,
                            Description = "Description for Ticket 33",
                            Priority = 2,
                            Status = 0,
                            Title = "Ticket 33"
                        },
                        new
                        {
                            TicketId = new Guid("bdaa10fc-be58-4b02-a1cc-c658dff4dcc8"),
                            AssetId = new Guid("cb7993e1-355c-4af1-9acc-bd7d49b96177"),
                            Category = 1,
                            Description = "Description for Ticket 34",
                            Priority = 0,
                            Status = 1,
                            Title = "Ticket 34"
                        },
                        new
                        {
                            TicketId = new Guid("63c5b7ea-8e90-4f7c-81f4-355cac7f17f6"),
                            AssetId = new Guid("e755ae09-7715-4a9c-b311-9cab13534e59"),
                            Category = 2,
                            Description = "Description for Ticket 35",
                            Priority = 1,
                            Status = 2,
                            Title = "Ticket 35"
                        },
                        new
                        {
                            TicketId = new Guid("557b578a-4a21-4436-ab62-95c0da93f208"),
                            AssetId = new Guid("e30b1963-42cf-47d3-9926-f8e4ffbe1021"),
                            Category = 3,
                            Description = "Description for Ticket 36",
                            Priority = 2,
                            Status = 3,
                            Title = "Ticket 36"
                        },
                        new
                        {
                            TicketId = new Guid("72966a4a-6375-4bd3-b415-ad838d400c76"),
                            AssetId = new Guid("2068321b-f4c2-47ee-853d-298dba676ab8"),
                            Category = 0,
                            Description = "Description for Ticket 37",
                            Priority = 0,
                            Status = 0,
                            Title = "Ticket 37"
                        },
                        new
                        {
                            TicketId = new Guid("856f2cbd-c49a-4feb-8a15-92d58b65e00e"),
                            AssetId = new Guid("810a0307-e4b4-4628-a81c-eec6c5f1d66d"),
                            Category = 1,
                            Description = "Description for Ticket 38",
                            Priority = 1,
                            Status = 1,
                            Title = "Ticket 38"
                        },
                        new
                        {
                            TicketId = new Guid("dd1f4dcc-910e-4e38-a975-8ef2fa627d38"),
                            AssetId = new Guid("5613d2de-c16d-4cdc-830e-2e4773614f48"),
                            Category = 2,
                            Description = "Description for Ticket 39",
                            Priority = 2,
                            Status = 2,
                            Title = "Ticket 39"
                        },
                        new
                        {
                            TicketId = new Guid("ffea308c-b5df-4aec-83ec-7678310fdc0d"),
                            AssetId = new Guid("e6b0147b-083c-426b-af19-ef8ab0afda67"),
                            Category = 3,
                            Description = "Description for Ticket 40",
                            Priority = 0,
                            Status = 3,
                            Title = "Ticket 40"
                        },
                        new
                        {
                            TicketId = new Guid("7d6142fa-beaa-461c-8750-43eca60588b5"),
                            AssetId = new Guid("8753f5c5-2f3e-4f38-97f4-2864a1735c85"),
                            Category = 0,
                            Description = "Description for Ticket 41",
                            Priority = 1,
                            Status = 0,
                            Title = "Ticket 41"
                        },
                        new
                        {
                            TicketId = new Guid("35bfea52-5858-4421-8aa8-87f297feca4c"),
                            AssetId = new Guid("f5129329-1cc5-4df9-b145-ae555e95e8f6"),
                            Category = 1,
                            Description = "Description for Ticket 42",
                            Priority = 2,
                            Status = 1,
                            Title = "Ticket 42"
                        },
                        new
                        {
                            TicketId = new Guid("50557b5f-84f1-4694-ae00-e0b998f5b352"),
                            AssetId = new Guid("0dd2ea81-25aa-4309-863a-b525e10d7160"),
                            Category = 2,
                            Description = "Description for Ticket 43",
                            Priority = 0,
                            Status = 2,
                            Title = "Ticket 43"
                        },
                        new
                        {
                            TicketId = new Guid("e136ff1e-c63b-48f3-ad68-5b4203108acc"),
                            AssetId = new Guid("5cc0e93e-fbc8-4068-9d92-2b33cd72b30f"),
                            Category = 3,
                            Description = "Description for Ticket 44",
                            Priority = 1,
                            Status = 3,
                            Title = "Ticket 44"
                        },
                        new
                        {
                            TicketId = new Guid("7a34b037-06f3-4813-8e19-6c8c73da3040"),
                            AssetId = new Guid("627b0b34-7836-4a70-be6f-af0d79c89723"),
                            Category = 0,
                            Description = "Description for Ticket 45",
                            Priority = 2,
                            Status = 0,
                            Title = "Ticket 45"
                        },
                        new
                        {
                            TicketId = new Guid("5f7540a8-31db-4f03-bc4b-a19a76dc44b3"),
                            AssetId = new Guid("1acaab62-c14e-4e99-b662-e4810572dcf3"),
                            Category = 1,
                            Description = "Description for Ticket 46",
                            Priority = 0,
                            Status = 1,
                            Title = "Ticket 46"
                        },
                        new
                        {
                            TicketId = new Guid("d5a13926-9ddf-465b-a21b-bc59c949bf4d"),
                            AssetId = new Guid("c3093c85-90fc-4943-9a5f-514ec11e005b"),
                            Category = 2,
                            Description = "Description for Ticket 47",
                            Priority = 1,
                            Status = 2,
                            Title = "Ticket 47"
                        },
                        new
                        {
                            TicketId = new Guid("4596c74a-ec71-4cc5-a168-85ad50ba56d8"),
                            AssetId = new Guid("45f9036e-e4bb-45a3-a68e-7577f2c94dd9"),
                            Category = 3,
                            Description = "Description for Ticket 48",
                            Priority = 2,
                            Status = 3,
                            Title = "Ticket 48"
                        },
                        new
                        {
                            TicketId = new Guid("bf84b3ae-d5cd-42f4-b237-4b1f8eb63581"),
                            AssetId = new Guid("9ba06a74-bacc-493e-beac-e8bb4a26c4b2"),
                            Category = 0,
                            Description = "Description for Ticket 49",
                            Priority = 0,
                            Status = 0,
                            Title = "Ticket 49"
                        },
                        new
                        {
                            TicketId = new Guid("a9e4c904-0c59-4e09-a076-d26141cd4e2d"),
                            AssetId = new Guid("74200675-537f-401a-bd14-9ea38d0ff550"),
                            Category = 1,
                            Description = "Description for Ticket 50",
                            Priority = 1,
                            Status = 1,
                            Title = "Ticket 50"
                        });
                });

            modelBuilder.Entity("TracklyApi.Models.Asset", b =>
                {
                    b.HasOne("TracklyApi.Models.Department", "Department")
                        .WithMany("Assets")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TracklyApi.Models.Location", "Location")
                        .WithMany("Assets")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TracklyApi.Models.Ticket", b =>
                {
                    b.HasOne("TracklyApi.Models.Asset", "Asset")
                        .WithMany("Tickets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TracklyApi.Models.Asset", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TracklyApi.Models.Department", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("TracklyApi.Models.Location", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
